version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  nats:
    image: nats
    ports:
      - "4222:4222"

  service1:
    build: ./service1
    volumes:
      - ./service1/:/go/src/app
    depends_on:
      - nats

  service2:
    build: ./service2
    volumes:
      - ./service2/:/go/src/app
    depends_on:
      - nats
      - redis
