version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  nats:
    image: nats
    ports:
      - "4222:4222"

  publisher:
    build: ./publisher
    volumes:
      - ./publisher/:/go/src/app
    depends_on:
      - nats
    ports:
      - "8080:8080"

  subscriber:
    build: ./subscriber
    volumes:
      - ./subscriber/:/go/src/app
    depends_on:
      - nats
      - redis
